### ISSUE TITLE
sometimes not save with the background image, just the drawing

### ISSUE THREAD

**Issue by Joao-b4** [ja2375/painter2#3]
This bug occurs to me, there are no parameters, sometimes when exporting as an image, there is simply no background image, just a drawing.
When I tried to make a version of the library you derived, I also had this problem, I try to fix this bug for months, but I have no idea why it happens  :<

**Comment by Joao-b4** [comment]
I found an issue in the flutter about it, it was fixed in version 1.7.8., but the problem came back in version 1.9.1, the issue is open and being resolved

https://github.com/flutter/flutter/issues/43085

**Comment by ja2375** [comment]
Te issue you mentioned was just closed some hours ago :)
